create type "public"."custom_field_type" as enum ('students', 'teams', 'orgs');

create table "public"."coaches" (
    "coach_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "email" text,
    "last_name" text,
    "org_id" bigint
);


alter table "public"."coaches" enable row level security;

create table "public"."custom_fields" (
    "custom_field_id" bigint generated by default as identity not null,
    "key" text not null,
    "label" text not null,
    "choices" text[],
    "help_text" text,
    "regex" text,
    "required" boolean,
    "editable" boolean,
    "hidden" boolean,
    "event_id" bigint,
    "type" custom_field_type not null
);


alter table "public"."custom_fields" enable row level security;

create table "public"."hosts" (
    "host_id" bigint generated by default as identity not null,
    "host_name" text
);


alter table "public"."hosts" enable row level security;

create table "public"."org_events" (
    "id" bigint generated by default as identity not null,
    "org_id" bigint,
    "event_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "join_code" text,
    "custom_fields" jsonb not null default '{}'::jsonb
);


alter table "public"."org_events" enable row level security;

create table "public"."orgs" (
    "org_id" bigint generated by default as identity not null,
    "name" text,
    "address" jsonb,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."orgs" enable row level security;

alter table "public"."events" add column "host_id" bigint;

alter table "public"."student_events" add column "custom_fields" jsonb not null default '{}'::jsonb;

alter table "public"."teams" add column "custom_fields" jsonb not null default '{}'::jsonb;

alter table "public"."teams" add column "join_code" text;

alter table "public"."teams" add column "org_id" bigint;

alter table "public"."tests" add column "access_rules" jsonb not null default '{}'::jsonb;

CREATE UNIQUE INDEX coaches_pkey ON public.coaches USING btree (coach_id);

CREATE UNIQUE INDEX custom_fields_pkey ON public.custom_fields USING btree (custom_field_id);

CREATE UNIQUE INDEX hosts_pkey ON public.hosts USING btree (host_id);

CREATE UNIQUE INDEX org_events_pkey ON public.org_events USING btree (id);

CREATE UNIQUE INDEX orgs_pkey ON public.orgs USING btree (org_id);

alter table "public"."coaches" add constraint "coaches_pkey" PRIMARY KEY using index "coaches_pkey";

alter table "public"."custom_fields" add constraint "custom_fields_pkey" PRIMARY KEY using index "custom_fields_pkey";

alter table "public"."hosts" add constraint "hosts_pkey" PRIMARY KEY using index "hosts_pkey";

alter table "public"."org_events" add constraint "org_events_pkey" PRIMARY KEY using index "org_events_pkey";

alter table "public"."orgs" add constraint "orgs_pkey" PRIMARY KEY using index "orgs_pkey";

alter table "public"."coaches" add constraint "coaches_org_id_fkey" FOREIGN KEY (org_id) REFERENCES orgs(org_id) ON DELETE SET NULL not valid;

alter table "public"."coaches" validate constraint "coaches_org_id_fkey";

alter table "public"."custom_fields" add constraint "custom_fields_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."custom_fields" validate constraint "custom_fields_event_id_fkey";

alter table "public"."events" add constraint "events_host_id_fkey" FOREIGN KEY (host_id) REFERENCES hosts(host_id) not valid;

alter table "public"."events" validate constraint "events_host_id_fkey";

alter table "public"."org_events" add constraint "org_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."org_events" validate constraint "org_events_event_id_fkey";

alter table "public"."org_events" add constraint "org_events_org_id_fkey" FOREIGN KEY (org_id) REFERENCES orgs(org_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."org_events" validate constraint "org_events_org_id_fkey";

alter table "public"."teams" add constraint "teams_org_id_fkey" FOREIGN KEY (org_id) REFERENCES orgs(org_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "teams_org_id_fkey";

grant delete on table "public"."coaches" to "anon";

grant insert on table "public"."coaches" to "anon";

grant references on table "public"."coaches" to "anon";

grant select on table "public"."coaches" to "anon";

grant trigger on table "public"."coaches" to "anon";

grant truncate on table "public"."coaches" to "anon";

grant update on table "public"."coaches" to "anon";

grant delete on table "public"."coaches" to "authenticated";

grant insert on table "public"."coaches" to "authenticated";

grant references on table "public"."coaches" to "authenticated";

grant select on table "public"."coaches" to "authenticated";

grant trigger on table "public"."coaches" to "authenticated";

grant truncate on table "public"."coaches" to "authenticated";

grant update on table "public"."coaches" to "authenticated";

grant delete on table "public"."coaches" to "service_role";

grant insert on table "public"."coaches" to "service_role";

grant references on table "public"."coaches" to "service_role";

grant select on table "public"."coaches" to "service_role";

grant trigger on table "public"."coaches" to "service_role";

grant truncate on table "public"."coaches" to "service_role";

grant update on table "public"."coaches" to "service_role";

grant delete on table "public"."custom_fields" to "anon";

grant insert on table "public"."custom_fields" to "anon";

grant references on table "public"."custom_fields" to "anon";

grant select on table "public"."custom_fields" to "anon";

grant trigger on table "public"."custom_fields" to "anon";

grant truncate on table "public"."custom_fields" to "anon";

grant update on table "public"."custom_fields" to "anon";

grant delete on table "public"."custom_fields" to "authenticated";

grant insert on table "public"."custom_fields" to "authenticated";

grant references on table "public"."custom_fields" to "authenticated";

grant select on table "public"."custom_fields" to "authenticated";

grant trigger on table "public"."custom_fields" to "authenticated";

grant truncate on table "public"."custom_fields" to "authenticated";

grant update on table "public"."custom_fields" to "authenticated";

grant delete on table "public"."custom_fields" to "service_role";

grant insert on table "public"."custom_fields" to "service_role";

grant references on table "public"."custom_fields" to "service_role";

grant select on table "public"."custom_fields" to "service_role";

grant trigger on table "public"."custom_fields" to "service_role";

grant truncate on table "public"."custom_fields" to "service_role";

grant update on table "public"."custom_fields" to "service_role";

grant delete on table "public"."hosts" to "anon";

grant insert on table "public"."hosts" to "anon";

grant references on table "public"."hosts" to "anon";

grant select on table "public"."hosts" to "anon";

grant trigger on table "public"."hosts" to "anon";

grant truncate on table "public"."hosts" to "anon";

grant update on table "public"."hosts" to "anon";

grant delete on table "public"."hosts" to "authenticated";

grant insert on table "public"."hosts" to "authenticated";

grant references on table "public"."hosts" to "authenticated";

grant select on table "public"."hosts" to "authenticated";

grant trigger on table "public"."hosts" to "authenticated";

grant truncate on table "public"."hosts" to "authenticated";

grant update on table "public"."hosts" to "authenticated";

grant delete on table "public"."hosts" to "service_role";

grant insert on table "public"."hosts" to "service_role";

grant references on table "public"."hosts" to "service_role";

grant select on table "public"."hosts" to "service_role";

grant trigger on table "public"."hosts" to "service_role";

grant truncate on table "public"."hosts" to "service_role";

grant update on table "public"."hosts" to "service_role";

grant delete on table "public"."org_events" to "anon";

grant insert on table "public"."org_events" to "anon";

grant references on table "public"."org_events" to "anon";

grant select on table "public"."org_events" to "anon";

grant trigger on table "public"."org_events" to "anon";

grant truncate on table "public"."org_events" to "anon";

grant update on table "public"."org_events" to "anon";

grant delete on table "public"."org_events" to "authenticated";

grant insert on table "public"."org_events" to "authenticated";

grant references on table "public"."org_events" to "authenticated";

grant select on table "public"."org_events" to "authenticated";

grant trigger on table "public"."org_events" to "authenticated";

grant truncate on table "public"."org_events" to "authenticated";

grant update on table "public"."org_events" to "authenticated";

grant delete on table "public"."org_events" to "service_role";

grant insert on table "public"."org_events" to "service_role";

grant references on table "public"."org_events" to "service_role";

grant select on table "public"."org_events" to "service_role";

grant trigger on table "public"."org_events" to "service_role";

grant truncate on table "public"."org_events" to "service_role";

grant update on table "public"."org_events" to "service_role";

grant delete on table "public"."orgs" to "anon";

grant insert on table "public"."orgs" to "anon";

grant references on table "public"."orgs" to "anon";

grant select on table "public"."orgs" to "anon";

grant trigger on table "public"."orgs" to "anon";

grant truncate on table "public"."orgs" to "anon";

grant update on table "public"."orgs" to "anon";

grant delete on table "public"."orgs" to "authenticated";

grant insert on table "public"."orgs" to "authenticated";

grant references on table "public"."orgs" to "authenticated";

grant select on table "public"."orgs" to "authenticated";

grant trigger on table "public"."orgs" to "authenticated";

grant truncate on table "public"."orgs" to "authenticated";

grant update on table "public"."orgs" to "authenticated";

grant delete on table "public"."orgs" to "service_role";

grant insert on table "public"."orgs" to "service_role";

grant references on table "public"."orgs" to "service_role";

grant select on table "public"."orgs" to "service_role";

grant trigger on table "public"."orgs" to "service_role";

grant truncate on table "public"."orgs" to "service_role";

grant update on table "public"."orgs" to "service_role";


