create type "public"."refund_status_enum" as enum ('PENDING', 'APPROVED', 'DENIED');

create table "public"."refund_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ticket_id" bigint,
    "refund_status" refund_status_enum,
    "message" text,
    "quantity" bigint not null
);


alter table "public"."refund_requests" enable row level security;

CREATE UNIQUE INDEX refund_requests_pkey ON public.refund_requests USING btree (id);

alter table "public"."refund_requests" add constraint "refund_requests_pkey" PRIMARY KEY using index "refund_requests_pkey";

alter table "public"."refund_requests" add constraint "refund_requests_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES ticket_orders(id) not valid;

alter table "public"."refund_requests" validate constraint "refund_requests_ticket_id_fkey";

grant delete on table "public"."refund_requests" to "anon";

grant insert on table "public"."refund_requests" to "anon";

grant references on table "public"."refund_requests" to "anon";

grant select on table "public"."refund_requests" to "anon";

grant trigger on table "public"."refund_requests" to "anon";

grant truncate on table "public"."refund_requests" to "anon";

grant update on table "public"."refund_requests" to "anon";

grant delete on table "public"."refund_requests" to "authenticated";

grant insert on table "public"."refund_requests" to "authenticated";

grant references on table "public"."refund_requests" to "authenticated";

grant select on table "public"."refund_requests" to "authenticated";

grant trigger on table "public"."refund_requests" to "authenticated";

grant truncate on table "public"."refund_requests" to "authenticated";

grant update on table "public"."refund_requests" to "authenticated";

grant delete on table "public"."refund_requests" to "service_role";

grant insert on table "public"."refund_requests" to "service_role";

grant references on table "public"."refund_requests" to "service_role";

grant select on table "public"."refund_requests" to "service_role";

grant trigger on table "public"."refund_requests" to "service_role";

grant truncate on table "public"."refund_requests" to "service_role";

grant update on table "public"."refund_requests" to "service_role";

alter table "public"."refund_requests" disable row level security;