create table "public"."suspected_cheaters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint,
    "student_id" uuid,
    "reason" text,
    "metadata" jsonb
);

CREATE UNIQUE INDEX suspected_cheaters_pkey ON public.suspected_cheaters USING btree (id);

alter table "public"."suspected_cheaters" add constraint "suspected_cheaters_pkey" PRIMARY KEY using index "suspected_cheaters_pkey";

alter table "public"."suspected_cheaters" add constraint "suspected_cheaters_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."suspected_cheaters" validate constraint "suspected_cheaters_event_id_fkey";

alter table "public"."suspected_cheaters" add constraint "suspected_cheaters_student_id_fkey" FOREIGN KEY (student_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."suspected_cheaters" validate constraint "suspected_cheaters_student_id_fkey";

set check_function_bodies = off;

grant delete on table "public"."suspected_cheaters" to "anon";

grant insert on table "public"."suspected_cheaters" to "anon";

grant references on table "public"."suspected_cheaters" to "anon";

grant select on table "public"."suspected_cheaters" to "anon";

grant trigger on table "public"."suspected_cheaters" to "anon";

grant truncate on table "public"."suspected_cheaters" to "anon";

grant update on table "public"."suspected_cheaters" to "anon";

grant delete on table "public"."suspected_cheaters" to "authenticated";

grant insert on table "public"."suspected_cheaters" to "authenticated";

grant references on table "public"."suspected_cheaters" to "authenticated";

grant select on table "public"."suspected_cheaters" to "authenticated";

grant trigger on table "public"."suspected_cheaters" to "authenticated";

grant truncate on table "public"."suspected_cheaters" to "authenticated";

grant update on table "public"."suspected_cheaters" to "authenticated";

grant delete on table "public"."suspected_cheaters" to "service_role";

grant insert on table "public"."suspected_cheaters" to "service_role";

grant references on table "public"."suspected_cheaters" to "service_role";

grant select on table "public"."suspected_cheaters" to "service_role";

grant trigger on table "public"."suspected_cheaters" to "service_role";

grant truncate on table "public"."suspected_cheaters" to "service_role";

grant update on table "public"."suspected_cheaters" to "service_role";