revoke delete on table "public"."guts_grades" from "anon";

revoke insert on table "public"."guts_grades" from "anon";

revoke references on table "public"."guts_grades" from "anon";

revoke select on table "public"."guts_grades" from "anon";

revoke trigger on table "public"."guts_grades" from "anon";

revoke truncate on table "public"."guts_grades" from "anon";

revoke update on table "public"."guts_grades" from "anon";

revoke delete on table "public"."guts_grades" from "authenticated";

revoke insert on table "public"."guts_grades" from "authenticated";

revoke references on table "public"."guts_grades" from "authenticated";

revoke select on table "public"."guts_grades" from "authenticated";

revoke trigger on table "public"."guts_grades" from "authenticated";

revoke truncate on table "public"."guts_grades" from "authenticated";

revoke update on table "public"."guts_grades" from "authenticated";

revoke delete on table "public"."guts_grades" from "service_role";

revoke insert on table "public"."guts_grades" from "service_role";

revoke references on table "public"."guts_grades" from "service_role";

revoke select on table "public"."guts_grades" from "service_role";

revoke trigger on table "public"."guts_grades" from "service_role";

revoke truncate on table "public"."guts_grades" from "service_role";

revoke update on table "public"."guts_grades" from "service_role";

alter table "public"."guts_grades" drop constraint "guts_grades_grader_id_fkey";

alter table "public"."guts_grades" drop constraint "guts_grades_team_id_fkey";

alter table "public"."guts_grades" drop constraint "guts_grades_test_id_fkey";

alter table "public"."guts_grades" drop constraint "guts_grades_test_problem_id_fkey";

alter table "public"."guts_grades" drop constraint "single_grade_per_team_problem";

alter table "public"."guts_grades" drop constraint "guts_grades_pkey";

drop index if exists "public"."guts_grades_pkey";

drop index if exists "public"."single_grade_per_team_problem";

drop table "public"."guts_grades";

create table "public"."manual_grades" (
    "guts_grade_id" bigint generated by default as identity not null,
    "graded_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "team_id" bigint not null,
    "test_problem_id" bigint not null,
    "answer_latex" text,
    "grader_id" uuid,
    "score" bigint,
    "status" text,
    "test_id" bigint
);


CREATE UNIQUE INDEX guts_grades_pkey ON public.manual_grades USING btree (guts_grade_id);

CREATE UNIQUE INDEX single_grade_per_team_problem ON public.manual_grades USING btree (team_id, test_problem_id);

alter table "public"."manual_grades" add constraint "guts_grades_pkey" PRIMARY KEY using index "guts_grades_pkey";

alter table "public"."manual_grades" add constraint "guts_grades_grader_id_fkey" FOREIGN KEY (grader_id) REFERENCES admins(admin_id) not valid;

alter table "public"."manual_grades" validate constraint "guts_grades_grader_id_fkey";

alter table "public"."manual_grades" add constraint "guts_grades_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(team_id) not valid;

alter table "public"."manual_grades" validate constraint "guts_grades_team_id_fkey";

alter table "public"."manual_grades" add constraint "guts_grades_test_id_fkey" FOREIGN KEY (test_id) REFERENCES tests(test_id) not valid;

alter table "public"."manual_grades" validate constraint "guts_grades_test_id_fkey";

alter table "public"."manual_grades" add constraint "guts_grades_test_problem_id_fkey" FOREIGN KEY (test_problem_id) REFERENCES test_problems(test_problem_id) not valid;

alter table "public"."manual_grades" validate constraint "guts_grades_test_problem_id_fkey";

alter table "public"."manual_grades" add constraint "single_grade_per_team_problem" UNIQUE using index "single_grade_per_team_problem";

grant delete on table "public"."manual_grades" to "anon";

grant insert on table "public"."manual_grades" to "anon";

grant references on table "public"."manual_grades" to "anon";

grant select on table "public"."manual_grades" to "anon";

grant trigger on table "public"."manual_grades" to "anon";

grant truncate on table "public"."manual_grades" to "anon";

grant update on table "public"."manual_grades" to "anon";

grant delete on table "public"."manual_grades" to "authenticated";

grant insert on table "public"."manual_grades" to "authenticated";

grant references on table "public"."manual_grades" to "authenticated";

grant select on table "public"."manual_grades" to "authenticated";

grant trigger on table "public"."manual_grades" to "authenticated";

grant truncate on table "public"."manual_grades" to "authenticated";

grant update on table "public"."manual_grades" to "authenticated";

grant delete on table "public"."manual_grades" to "service_role";

grant insert on table "public"."manual_grades" to "service_role";

grant references on table "public"."manual_grades" to "service_role";

grant select on table "public"."manual_grades" to "service_role";

grant trigger on table "public"."manual_grades" to "service_role";

grant truncate on table "public"."manual_grades" to "service_role";

grant update on table "public"."manual_grades" to "service_role";
